### ISSUE TITLE
Arquivo faltando informações

### ISSUE THREAD

**Issue by thiagocrutfpr** [rgmantovani/dataStructures2#10]
No Arquivo de input3.txt da atividade 2, o jogo Overwatch 2 está faltando uma informação (Mídia).
No Arquivo de op3.txt da atividade 2, o jogo Bloons TD 6 está faltando uma informação (Preço).

**Comment by rgmantovani** [comment]
Resolvido aqui: c2597d744e4854ce8a94ee69f690adabf7c8610b
